In [14]:
import torch
from torch import nn

In [15]:
input_tensor = torch.tensor([[0.3571, 0.5000, 0.6429]])

In [16]:
#Define our first linear layer
linear_layer = nn.Linear(in_features=3, out_features=2)

In [17]:
#pass input tensor through the linear layer
output = linear_layer(input_tensor)
print(output)

tensor([[ 1.0790, -0.3026]], grad_fn=<AddmmBackward0>)


In [18]:
linear_layer.weight

Parameter containing:
tensor([[ 0.4093,  0.4810,  0.2020],
        [-0.5382,  0.1163,  0.1046]], requires_grad=True)

In [19]:
linear_layer.bias

Parameter containing:
tensor([ 0.5625, -0.2359], requires_grad=True)

In [20]:
model = nn.Sequential(
    nn.Linear(10, 18),
    nn.Linear(18, 20),
    nn.Linear(20, 5)
)

In [21]:
print(input_tensor)

tensor([[0.3571, 0.5000, 0.6429]])


In [22]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(
    nn.Linear(8, 5),
    nn.Linear(5, 1)
                     )

output = model(input_tensor)
print(output)

tensor([[-0.8497]], grad_fn=<AddmmBackward0>)


In [23]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device


In [25]:
input_tensor = torch.tensor([[6.0]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

tensor([[0.9975]])


In [ ]:
model = nn.Sequential(
    nn.Linear(1, 13),
    nn.Linear(13, 1),
    nn.Sigmoid()
)

In [ ]:
softmax = nn.Softmax(dim=-1) #dim=-1 means that the softmax is applied to the last dimension of the input tensor
output = softmax(input_tensor)

In [26]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


In [29]:
#foward pass
# create input data of shape 5X6
n_classes = 3
input_tensor = torch.randn(5, 6)

# create binary classification model

model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, n_classes),
    nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

tensor([[0.4911, 0.1537, 0.3552],
        [0.4521, 0.2056, 0.3422],
        [0.4789, 0.2459, 0.2752],
        [0.5212, 0.2782, 0.2006],
        [0.4696, 0.2454, 0.2850]], grad_fn=<SoftmaxBackward0>)


In [30]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.0461]], grad_fn=<SigmoidBackward0>)


In [ ]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 8),
    nn.Linear(8, 6),
    nn.Linear(6, 4),
    nn.Linear(4, 1)
    )

output = model(input_tensor)
print(output)

In [31]:
y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([0, 1, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes)

In [ ]:
import torch.nn.functional as F

y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])

# Create the cross entropy loss function
criterion = nn.CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

In [ ]:
criterion = nn.CrossEntropyLoss()

# Calculate the loss
loss = criterion(scores.double(), one_hot_label.double())

# Compute the gradients of the loss
loss.backward()

# Display gradients of the weight and bias tensors in order
print(model[0].weight.grad)
print(model[0].bias.grad)

criterion = nn.CrossEntropyLoss()

# Calculate the loss
loss = criterion(preds, target)

# Compute the gradients of the loss
loss.backward()

# Display gradients of the weight and bias tensors in order
print(weight.grad)
print(bias.grad)