In [1]:
import numpy as np

In [2]:
#1. Create a vector (1D array) of size 20. All the elements are initialized with 0 (zero) 
# except for the 8th element that is set with the value 8.
vector = np.zeros(20)
vector[7] = 8
print(vector)


[0. 0. 0. 0. 0. 0. 0. 8. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#2. Create a vector of size 16 with random values ranging from 0 to 63, print the vector, 
# then sort it and print the vector again.
vector = np.random.randint(0, 64, 16)
print('Before sort')
print(vector)

vector.sort()
print('After sort')
print(vector)

Before sort
[38 19  2 37 53 21 15 18 31 17 38 27  8 17 27 38]
After sort
[ 2  8 15 17 17 18 19 21 27 27 31 37 38 38 38 53]


In [7]:
#3. Create a 5x5 matrix with values ranging from 0 to 24.
matrix = np.arange(25).reshape(5, 5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [8]:
#4. Create an 8x8 array with random values, then find the min and max values stored in this matrix.
matrix = np.random.randint(0, 100, (8, 8))
print(matrix)

print('Min:', matrix.min())
print('Max:', matrix.max())


[[17 57  5 67 10 75 65 24]
 [ 3 53 74 46 65 20 34 71]
 [ 7 39 63 33 69 48 19 29]
 [77 20 93  5 37 78 75  9]
 [53 98 58 75 90  1 72 82]
 [49 63 74  2 81 15 90 53]
 [36 38 83 53 89 28 84 36]
 [23  3 59 72 33 99 82 95]]
Min: 1
Max: 99


In [9]:
#5. Create a vector of size 32 that is initialized with random values inside the range (0, 99) 
# and then find the mean of all the initial values.
vector = np.random.randint(0, 100, 32)
print(vector)
print('Mean:', vector.mean())


[49 25 36 88  2 16 19 89 11 35  8 43 66 62 36 28  9 96 47 47 60 82 92 12
 94  0 48  5 39 69 89 17]
Mean: 44.34375
