
                                                                    Binaim Abebe
##### 4.	PART IV: TensorFlow Code in Jupyter Notebook (20 Points)


In [20]:
import tensorflow as tf
import numpy as np

#disable warning
Warning = False

#version 
print(tf.__version__)

1.15.5


In [21]:
#TO-DO
#--) Write TensorFlow code to provide the solutions to the following simple problems:
#1.	Declare two constant tensors that have the values of 15 and 45. Add these two tensors and print out the results.

#Declare two constant tensors that have the values of 15 and 45
tensor1 = tf.constant(15)
tensor2 = tf.constant(45)

#call seesion
with tf.Session() as sess:
    #print out the results
    result = sess.run(tensor1 + tensor2)
    ##Add these two tensors and print out the results
    print("Addition of two tensors: ", result)



Addition of two tensors:  60


In [22]:
#2.	Declare two variable tensors, a and b, that are initialized with scalar values of 2.75 and 8.5. Find their product and print out the result.

#Declare two variable tensors, a and b, that are initialized with scalar values of 2.75 and 8.5
a = tf.Variable(2.75)
b = tf.Variable(8.5)

with tf.Session() as sess:
    #initialize the variables
    init = tf.global_variables_initializer()
    sess.run(init)
    #Find their product and print out the result
    result = sess.run(a*b)
    print("Product of two tensors: ", result)


Product of two tensors:  23.375


In [23]:
#3.	Create two placeholders: x and y - that are both scalars of 32-bit floats. Assign 5.25 to x and 12.6 to y, multiply them together, and print out the results.

#Create two placeholders: x and y - that are both scalars of 32-bit floats
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

with tf.Session() as sess:
    #Assign 5.25 to x and 12.6 to y
    result = sess.run(x*y, feed_dict={x: 5.25, y: 12.6})
    #multiply them together, and print out the results
    print("Product of two placeholders: ", result)


Product of two placeholders:  66.15


In [24]:
#4.	Create one placeholder: z - that is an N-Dimensional array (N can be >= 1) that can have any shape (shape = None). Feed this vector [1, 3, 5, 7, 9] into z and multiply it by 3. Display the results.

#Create one placeholder: z - that is an N-Dimensional array (N can be >= 1) that can have any shape (shape = None).
z = tf.placeholder(tf.float32, shape=[None])

with tf.Session() as sess:
    #Feed this vector [1, 3, 5, 7, 9] into z
    result = sess.run(z*3, feed_dict={z: [1, 3, 5, 7, 9]})
    #multiply it by 3. Display the results
    print("Product of one placeholder: ", result)

Product of one placeholder:  [ 3.  9. 15. 21. 27.]


In [25]:
#5.	Create a constant tensor that is a matrix of the shape (8, 8). The matrix is initialized with all ones (1)
# Create a variable tensor that is also a matrix of the shape (8, 8) and initialized with random integer values between 0 and 99. 
# Add these two tensors and display the results.

#Create a constant tensor that is a matrix of the shape (8, 8). The matrix is initialized with all ones (1)
matrix1 = tf.constant(1, shape=[8, 8])

#Create a variable tensor that is also a matrix of the shape (8, 8) and initialized with random integer values between 0 and 99.
matrix2 = tf.Variable(tf.random_uniform([8, 8], 0, 99, dtype=tf.int32))

with tf.Session() as sess:
    #initialize the variables
    init = tf.global_variables_initializer()
    sess.run(init)
    #Add these two tensors and display the results
    result = sess.run(matrix1 + matrix2)
    print("Addition of two matrix: \n", result)



Addition of two matrix: 
 [[94 74 33 85 41 81 38 84]
 [62 66 45 57 66 91 79 13]
 [19 71 40 23 36 11 97 13]
 [89 83 61 68 37 14 93 33]
 [30 44 12 32 65 90 82 55]
 [61 50 95 25 68 14 11 63]
 [68 24 62 25 53  4 11 61]
 [ 4 67  2 43 74 68 33 76]]
